import DogGallery from "@/components/aboutUs/DogGallery";

const dogImages = [
  "/images/aboutUs/gallery/539b2787-957f-434a-96aa-39b098870a8b.JPEG",
  "/images/aboutUs/gallery/FullSizeRender 2.jpeg",
  "/images/aboutUs/gallery/FullSizeRender 3.jpeg",
  "/images/aboutUs/gallery/FullSizeRender 4.jpeg",
  "/images/aboutUs/gallery/FullSizeRender.jpeg",
  "/images/aboutUs/gallery/IMG_0162.jpeg",
  "/images/aboutUs/gallery/IMG_0163.jpeg",
  "/images/aboutUs/gallery/dogs3.jpeg",
  "/images/aboutUs/gallery/IMG_0319.jpeg",
  "/images/aboutUs/gallery/IMG_0322.jpeg",
  "/images/aboutUs/gallery/IMG_0372.jpeg",
  "/images/aboutUs/gallery/IMG_0706.JPEG",
  "/images/aboutUs/gallery/IMG_0878.jpeg",
  "/images/aboutUs/gallery/IMG_1113.jpeg",
  "/images/aboutUs/gallery/IMG_1335.jpeg",
  "/images/aboutUs/gallery/IMG_1389.jpeg",
  "/images/aboutUs/gallery/IMG_1568.jpeg",
  "/images/aboutUs/gallery/IMG_1657.JPEG",
  "/images/aboutUs/gallery/IMG_2367.jpeg",
  "/images/aboutUs/gallery/IMG_2430.jpeg",
  "/images/aboutUs/gallery/IMG_2639.jpeg",
  "/images/aboutUs/gallery/IMG_2860.jpeg",
  "/images/aboutUs/gallery/IMG_3115.jpeg",
  "/images/aboutUs/gallery/IMG_3163.jpeg",
  "/images/aboutUs/gallery/IMG_3212.jpeg",
  "/images/aboutUs/gallery/IMG_3214.jpeg",
  "/images/aboutUs/gallery/IMG_3270.jpeg",
  "/images/aboutUs/gallery/IMG_3337.jpeg",
  "/images/aboutUs/gallery/IMG_3678.jpeg",
  "/images/aboutUs/gallery/IMG_3835.jpeg",
  "/images/aboutUs/gallery/IMG_3839.jpeg",
  "/images/aboutUs/gallery/IMG_3870.JPEG",
  "/images/aboutUs/gallery/IMG_3871.JPEG",
  "/images/aboutUs/gallery/IMG_3907.jpeg",
  "/images/aboutUs/gallery/IMG_3909.jpeg",
  "/images/aboutUs/gallery/IMG_4253.jpeg",
  "/images/aboutUs/gallery/IMG_5277.jpeg",
  "/images/aboutUs/gallery/IMG_5546.JPEG",
  "/images/aboutUs/gallery/IMG_5551.JPEG",
  "/images/aboutUs/gallery/IMG_5555.jpeg",
  "/images/aboutUs/gallery/IMG_5697.jpeg",
  "/images/aboutUs/gallery/IMG_5962.jpeg",
  "/images/aboutUs/gallery/IMG_6145.jpeg",
  "/images/aboutUs/gallery/IMG_6542.jpeg",
  "/images/aboutUs/gallery/IMG_6695.jpeg",
  "/images/aboutUs/gallery/IMG_6739.jpeg",
  "/images/aboutUs/gallery/IMG_6747.jpeg",
  "/images/aboutUs/gallery/IMG_6987.jpeg",
  "/images/aboutUs/gallery/IMG_7053.jpeg",
  "/images/aboutUs/gallery/IMG_7057.jpeg",
  "/images/aboutUs/gallery/IMG_7325.jpeg",
  "/images/aboutUs/gallery/IMG_7332.jpeg",
  "/images/aboutUs/gallery/IMG_7334.jpeg",
  "/images/aboutUs/gallery/IMG_7514.jpeg",
  "/images/aboutUs/gallery/IMG_7687.jpeg",
  "/images/aboutUs/gallery/IMG_8166.jpeg",
  "/images/aboutUs/gallery/IMG_8175.jpeg",
  "/images/aboutUs/gallery/IMG_8735.jpeg",
  "/images/aboutUs/gallery/IMG_8952.jpeg",
  "/images/aboutUs/gallery/IMG_8980.jpeg",
  "/images/aboutUs/gallery/IMG_9910.jpeg",
  "/images/aboutUs/gallery/IMG_9919.JPEG",
  "/images/aboutUs/gallery/IMG_9976.jpeg",
];

export default function Home() {
  return <DogGallery images={dogImages} />;
}
